import Head from "next/head";
import Footer from "../components/footer/footer";
import Header from "../components/header/header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page of Forhever!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <div className="min-h-screen flex flex-col bg-slate-200">
        <Header />
      </div>
      <div className="mt-auto">
        <Footer />
      </div>
    </div>
  );
}
