import Head from "next/head";
import Image from "next/image";
import Header from "../components/header/header";
import Component from "../components/header/header-components/singin";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>This is homepage</h1>
    </div>
  );
}
